
--Gets tables and column info
SELECT 
	TABLE_SCHEMA, 
	TABLE_NAME, 
	COLUMN_NAME, 
	DATA_TYPE, 
	CHARACTER_MAXIMUM_LENGTH, 
	NUMERIC_PRECISION,
	IS_NULLABLE, 
	Case 
		When COLUMN_DEFAULT is null Then 0
		When len(COLUMN_DEFAULT) > 0 Then 1
		Else 0
	End COLUMN_DEFAULT
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'dbo'
Order by TABLE_NAME
