
--Gets tables and column info
SELECT 
	TABLE_SCHEMA, 
	TABLE_NAME, 
	COLUMN_NAME, 
	DATA_TYPE, 
	CHARACTER_MAXIMUM_LENGTH, 
	IS_NULLABLE, 
	NUMERIC_PRECISION
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'dbo'
Order by TABLE_NAME
